### ISSUE TITLE
SSL Cert problem

### ISSUE THREAD

**Issue by StartInno** [radical-squared/aquatemp#17]
Hi there

Aquatemp plugin as been installed ok and loads up controls. However power on button gives the below SSL Cert issue.

I can connect directly and uses On controls through the Aquatemp Ok.

Failed to call service climate/set_hvac_mode. Cannot connect to host cloud.linked-go.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL:CERTIFICATE_VERIFY_FAILED] certificate verify failed:
unable to get local issuer certificate ( ssl.c:1002)")

![IMG_6866](https://user-images.githubusercontent.com/10043026/233905575-7cad5a13-b9d9-456d-8c36-7064a111ba98.jpeg)

Logs:
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/aquatemp/climate.py:217 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: April 22, 2023, 18:14:18 (10 occurrences) 
Last logged: 15:07:25

[4977146832] Cannot connect to host cloud.linked-go.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]
[4954995280] Cannot connect to host cloud.linked-go.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]
[4986031696] Cannot connect to host cloud.linked-go.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]
[4988699280] Cannot connect to host cloud.linked-go.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]
[4997051536] Cannot connect to host cloud.linked-go.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 574, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 556, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/Users/danielswan/.homeassistant/custom_components/aquatemp/climate.py", line 217, in async_set_hvac_mode
    async with session.post(CONTROL_PATH, headers = self._headers, json=data) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host cloud.linked-go.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]

Also noting:

This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/aquatemp/climate.py:241 
Integration: aquatemp (documentation) 
First occurred: April 22, 2023, 18:32:01 (7 occurrences) 
Last logged: April 23, 2023, 08:14:57

Error executing service: <ServiceCall climate.set_fan_mode (c:01GYM1EY1YVV85GXEZYYFEJS77): entity_id=['climate.aquatemp'], fan_mode=low>
Error executing service: <ServiceCall climate.set_fan_mode (c:01GYM1F09H57JEDJZJEC7X32KF): entity_id=['climate.aquatemp'], fan_mode=auto>
Error executing service: <ServiceCall climate.set_fan_mode (c:01GYM1F1CBVMTGSXZRYZ08ZF7H): entity_id=['climate.aquatemp'], fan_mode=low>
Error executing service: <ServiceCall climate.set_fan_mode (c:01GYNGHGFJ7S9S7FZP2QK7WKZR): entity_id=['climate.aquatemp'], fan_mode=low>
Error executing service: <ServiceCall climate.set_fan_mode (c:01GYNGHNZ8M1M0VMBTW4R5XP8Y): entity_id=['climate.aquatemp'], fan_mode=low>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 574, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 556, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/core.py", line 1838, in catch_exceptions
    await coro_or_task
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/Users/danielswan/.homeassistant/custom_components/aquatemp/climate.py", line 241, in async_set_fan_mode
    async with session.post(CONTROL_PATH, headers = self._headers, json=data) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host cloud.linked-go.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]

**Comment by elad-bar** [comment]
fixed in v3.0.1, pls check and update

thanks

**Comment by elad-bar** [comment]
Closing the issue, if still relevant, please open another issue with details and logs

Thanks

**Comment by StartInno** [comment]
Great! All working. Thx
