### ISSUE TITLE
Error when my device is off

### ISSUE THREAD

**Issue by legantois** [radical-squared/aquatemp#23]
Dear community

when my heat pump is switched to off (using aqua temp app our HA) an error occurs every minute, 

2023-05-25 10:38:42.410 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 204, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/config/custom_components/aqua_temp/climate.py", line 177, in _handle_coordinator_update
    self._attr_target_temperature = float(str(target_temperature))
ValueError: could not convert string to float: 'None'

and no update is done in HA on any sensors (meaning that the device is still shown as ON and other attributes are frozen)

help pls 👍

**Comment by elad-bar** [comment]
fixed in v3.0.1, pls check and update

thanks

**Comment by legantois** [comment]
Thx off is now well managed with no more errors

Few Warnings at startup
2023-05-29 09:50:59.872 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.pompe_piscine_4_way_valve_output (<class 'custom_components.aqua_temp.sensor.AquaTempSensorEntity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('voltage') it is using; expected one of ['V', 'mV']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-05-29 09:50:59.886 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.pompe_piscine_electronic_expansion_valve_1_output (<class 'custom_components.aqua_temp.sensor.AquaTempSensorEntity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('voltage') it is using; expected one of ['V', 'mV']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-05-29 09:50:59.888 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.pompe_piscine_electronic_expansion_valve_2_output (<class 'custom_components.aqua_temp.sensor.AquaTempSensorEntity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('voltage') it is using; expected one of ['V', 'mV']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by elad-bar** [comment]
this is another issue, will be fixed in v3.0.2 (currently under testing),
can you pls close the issue? (you can open another one for the warning messages)

**Comment by legantois** [comment]
OK many thx
