### ISSUE TITLE
Solved: Integration not working after upgrade to "Home Assistant OS 14.2"

### ISSUE THREAD

**Issue by janosch74** [radical-squared/aquatemp#96]
I use V3.0.36, API Hitemp
Until Yesterday the integration worked perfectly.
After upgrading to "Home Assistant OS 14.0.rc1" the entities are not available anymore.
I tried reinstal, reload, reboot...

**Comment by jum** [comment]
I Have home assistant 2025.1.0 running, and I am seeing the same problem. I believe the initialization is failing due to some login code not running "async enough" while home assistant is starting up. I am unfortunately not yet fluent enough with the home assistant internals for further diagnosis.

I do see the following in may log:

```
2025-01-06 20:16:40.271 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration edata which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-06 20:16:40.274 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-06 20:16:40.276 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration aqua_temp which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-06 20:16:40.278 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration blitzortung which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-06 20:16:40.280 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration battery_notes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-06 20:16:40.282 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-06 20:16:50.287 DEBUG (MainThread) [custom_components.aqua_temp.managers.aqua_temp_config_manager] Storing config data: {"temperature_unit": {}}, Exiting: {"temperature_unit": {}}
2025-01-06 20:16:50.403 DEBUG (MainThread) [custom_components.aqua_temp.managers.aqua_temp_config_manager] Initialized, Entity Descriptions: 3, protocol codes: 3, protocol codes configuration: 3, platforms: 4, HVAC modes: {'default': {'off': None, 'cool': '0', 'heat': '1', 'auto': '2'}, '1245226668902080512': {'off': None, 'heat': '0'}, '1442284873216843776': {'off': None, 'cool': '0', 'heat': '1', 'auto': '2'}}, HVAC modes - reversed: {'default': {None: 'off', '0': 'cool', '1': 'heat', '2': 'auto'}, '1245226668902080512': {None: 'off', '0': 'heat'}, '1442284873216843776': {None: 'off', '0': 'cool', '1': 'heat', '2': 'auto'}}, Fan modes: {'default': {'auto': '0', 'low': '1'}, '1245226668902080512': {'off': '0', 'low': '1', 'high': '2'}, '1442284873216843776': {'auto': '0', 'low': '1'}}, Fan modes - reversed: {'default': {'0': 'auto', '1': 'low'}, '1245226668902080512': {'0': 'off', '1': 'low', '2': 'high'}, '1442284873216843776': {'0': 'auto', '1': 'low'}}
2025-01-06 20:16:50.414 INFO (MainThread) [custom_components.aqua_temp] Finished loading integration
2025-01-06 20:17:03.006 DEBUG (MainThread) [custom_components.aqua_temp.managers.aqua_temp_coordinator] Initializing coordinator
2025-01-06 20:17:03.043 INFO (MainThread) [custom_components.aqua_temp.managers.aqua_temp_coordinator] Start loading aqua_temp integration, Entry ID: f0b58693fac1874762f597c0a5d7e157
2025-01-06 20:17:03.043 DEBUG (MainThread) [custom_components.aqua_temp.managers.aqua_temp_api] Initializing API, Throw Error: True
2025-01-06 20:17:03.044 DEBUG (MainThread) [custom_components.aqua_temp.managers.aqua_temp_api] No token available, Login AquaTemp API and fetching devices
2025-01-06 20:17:04.116 DEBUG (MainThread) [custom_components.aqua_temp.managers.aqua_temp_api] Request to https://cloud.linked-go.com/cloudservice/api/app/user/login.json, Body: {'user_name': 'myemail@gmail.com', 'password': 'myhexpasswd'}, Result: {'error_code': '-1', 'error_msg': 'Error username or password', 'error_msg_code': '', 'is_reuslt_suc': False}
2025-01-06 20:17:18.009 WARNING (MainThread) [homeassistant.core] Something is blocking Home Assistant from wrapping up the start up phase. We're going to continue anyway. Please report the following info at https://github.com/home-assistant/core/issues: midea_ac.number, cast, braviatv.media_player, mqtt.sensor, usb, lovelace, mobile_app.sensor, midea_ac.button, webhook, battery_notes.button, fritzbox.sensor, schedule, tts, scene, androidtv_remote.media_player, ibeacon.sensor, hacs.update, midea_ac.switch, braviatv.remote, go2rtc, upnp.sensor, analytics, trace, edata, onboarding, binary_sensor, androidtv_remote.remote, dlna_dmr, bluetooth, battery_notes, light, network, weather, fritzbox.light, bluetooth_adapters, blueprint, mqtt.light, input_boolean, device_automation, braviatv, blitzortung.geo_location, homekit_controller.button, ffmpeg, fritz.image, conversation, upnp, search, cloud, energy.sensor, mqtt.binary_sensor, intent, fritzbox.binary_sensor, mqtt.switch, notify, group, input_datetime, diagnostics, mqtt.button, fritzbox.switch, ibeacon, mqtt, number, fritzbox.cover, fritz.sensor, tag, backup, met.weather, config, fritz.update, aqua_temp.sensor, workday, sun.sensor, hacs.switch, http, androidtv_remote, fritz, workday.binary_sensor, image, homekit_controller.media_player, aqua_temp.climate, fritz.binary_sensor, aqua_temp.select, repairs, automation, fritz.switch, input_select, google_translate.tts, system_log, geo_location, ibeacon.device_tracker, cloud.tts, counter, media_player, cast.media_player, mqtt.select, input_text, wake_word, input_button, battery_notes.sensor, edata.sensor, default_config, edata.button, hardware, fritzbox.climate, image_upload, sensor, my, battery_notes.binary_sensor, stream, songpal.media_player, ecowitt, logger, mqtt.update, frontend, mobile_app, homekit, websocket_api, climate, assist_pipeline, energy, dhcp, fritz.button, mobile_app.notify, midea_ac.binary_sensor, hacs, file_upload, person, switch, blitzortung.sensor, blitzortung, stt, select, media_source, sun, homeassistant, midea_ac.select, application_credentials, button, google_translate, dlna_dms, recorder, homeassistant_alerts, fritz.device_tracker, zone, songpal, script, cover, mobile_app.binary_sensor, system_health, homekit_controller, ssdp, aqua_temp.binary_sensor, history, radio_browser, homekit_controller.switch, dlna_dmr.media_player, midea_ac.climate, api, device_tracker, homeassistant.scene, ecowitt.sensor, met, upnp.binary_sensor, braviatv.button, remote, midea_ac.sensor, persistent_notification, fritzbox, camera, timer, mobile_app.device_tracker, ecowitt.binary_sensor, logbook, update, fritzbox.button, mqtt.scene, midea_ac, auth, zeroconf, aqua_temp, input_number The system is waiting for tasks: {<Task pending name='Task-344' coro=<DataUpdateCoordinator.async_refresh() running at /usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:355> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.13/asyncio/futures.py:384, <1 more>, Task.task_wakeup()]> cb=[set.remove()]>}
2025-01-06 20:17:18.054 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/aqua_temp/managers/aqua_temp_coordinator.py", line 59, in on_home_assistant_start
    await self.initialize()
  File "/config/custom_components/aqua_temp/managers/aqua_temp_coordinator.py", line 70, in initialize
    await self._api.initialize()
  File "/config/custom_components/aqua_temp/managers/aqua_temp_api.py", line 107, in initialize
    raise lex
  File "/config/custom_components/aqua_temp/managers/aqua_temp_api.py", line 103, in initialize
    await self._connect()
  File "/config/custom_components/aqua_temp/managers/aqua_temp_api.py", line 125, in _connect
    await self._login()
  File "/config/custom_components/aqua_temp/managers/aqua_temp_api.py", line 527, in _login
    raise LoginError()
custom_components.aqua_temp.models.exceptions.LoginError: Failed to login

```

For being able to better see the debug logging, I added the following to the manifest.json:
```
  "loggers": ["custom_components.aqua_temp"],
```

**Comment by janosch74** [comment]
After delete and reinstall the integration works again...
